import { Country } from 'types';

export const countries: Country[] = [
  { cca2: 'US', name: 'United States', callingCode: ['1'] },
  { cca2: 'GB', name: 'United Kingdom', callingCode: ['44'] },
  { cca2: 'CA', name: 'Canada', callingCode: ['1'] },
  { cca2: 'AU', name: 'Australia', callingCode: ['61'] },
  { cca2: 'DE', name: 'Germany', callingCode: ['49'] },
  { cca2: 'FR', name: 'France', callingCode: ['33'] },
  { cca2: 'IT', name: 'Italy', callingCode: ['39'] },
  { cca2: 'ES', name: 'Spain', callingCode: ['34'] },
  { cca2: 'NL', name: 'Netherlands', callingCode: ['31'] },
  { cca2: 'BE', name: 'Belgium', callingCode: ['32'] },
  { cca2: 'CH', name: 'Switzerland', callingCode: ['41'] },
  { cca2: 'AT', name: 'Austria', callingCode: ['43'] },
  { cca2: 'SE', name: 'Sweden', callingCode: ['46'] },
  { cca2: 'NO', name: 'Norway', callingCode: ['47'] },
  { cca2: 'DK', name: 'Denmark', callingCode: ['45'] },
  { cca2: 'FI', name: 'Finland', callingCode: ['358'] },
  { cca2: 'PL', name: 'Poland', callingCode: ['48'] },
  { cca2: 'CZ', name: 'Czech Republic', callingCode: ['420'] },
  { cca2: 'HU', name: 'Hungary', callingCode: ['36'] },
  { cca2: 'RO', name: 'Romania', callingCode: ['40'] },
  { cca2: 'BG', name: 'Bulgaria', callingCode: ['359'] },
  { cca2: 'HR', name: 'Croatia', callingCode: ['385'] },
  { cca2: 'SI', name: 'Slovenia', callingCode: ['386'] },
  { cca2: 'SK', name: 'Slovakia', callingCode: ['421'] },
  { cca2: 'LT', name: 'Lithuania', callingCode: ['370'] },
  { cca2: 'LV', name: 'Latvia', callingCode: ['371'] },
  { cca2: 'EE', name: 'Estonia', callingCode: ['372'] },
  { cca2: 'IE', name: 'Ireland', callingCode: ['353'] },
  { cca2: 'PT', name: 'Portugal', callingCode: ['351'] },
  { cca2: 'GR', name: 'Greece', callingCode: ['30'] },
  { cca2: 'CY', name: 'Cyprus', callingCode: ['357'] },
  { cca2: 'MT', name: 'Malta', callingCode: ['356'] },
  { cca2: 'LU', name: 'Luxembourg', callingCode: ['352'] },
  { cca2: 'IS', name: 'Iceland', callingCode: ['354'] },
  { cca2: 'LI', name: 'Liechtenstein', callingCode: ['423'] },
  { cca2: 'MC', name: 'Monaco', callingCode: ['377'] },
  { cca2: 'SM', name: 'San Marino', callingCode: ['378'] },
  { cca2: 'VA', name: 'Vatican City', callingCode: ['379'] },
  { cca2: 'AD', name: 'Andorra', callingCode: ['376'] },
  { cca2: 'JP', name: 'Japan', callingCode: ['81'] },
  { cca2: 'KR', name: 'South Korea', callingCode: ['82'] },
  { cca2: 'CN', name: 'China', callingCode: ['86'] },
  { cca2: 'IN', name: 'India', callingCode: ['91'] },
  { cca2: 'BR', name: 'Brazil', callingCode: ['55'] },
  { cca2: 'MX', name: 'Mexico', callingCode: ['52'] },
  { cca2: 'AR', name: 'Argentina', callingCode: ['54'] },
  { cca2: 'CL', name: 'Chile', callingCode: ['56'] },
  { cca2: 'CO', name: 'Colombia', callingCode: ['57'] },
  { cca2: 'PE', name: 'Peru', callingCode: ['51'] },
  { cca2: 'VE', name: 'Venezuela', callingCode: ['58'] },
  { cca2: 'EC', name: 'Ecuador', callingCode: ['593'] },
  { cca2: 'BO', name: 'Bolivia', callingCode: ['591'] },
  { cca2: 'PY', name: 'Paraguay', callingCode: ['595'] },
  { cca2: 'UY', name: 'Uruguay', callingCode: ['598'] },
  { cca2: 'GY', name: 'Guyana', callingCode: ['592'] },
  { cca2: 'SR', name: 'Suriname', callingCode: ['597'] },
  { cca2: 'FK', name: 'Falkland Islands', callingCode: ['500'] },
  { cca2: 'GF', name: 'French Guiana', callingCode: ['594'] },
  { cca2: 'RU', name: 'Russia', callingCode: ['7'] },
  { cca2: 'UA', name: 'Ukraine', callingCode: ['380'] },
  { cca2: 'BY', name: 'Belarus', callingCode: ['375'] },
  { cca2: 'MD', name: 'Moldova', callingCode: ['373'] },
  { cca2: 'GE', name: 'Georgia', callingCode: ['995'] },
  { cca2: 'AM', name: 'Armenia', callingCode: ['374'] },
  { cca2: 'AZ', name: 'Azerbaijan', callingCode: ['994'] },
  { cca2: 'KZ', name: 'Kazakhstan', callingCode: ['7'] },
  { cca2: 'UZ', name: 'Uzbekistan', callingCode: ['998'] },
  { cca2: 'KG', name: 'Kyrgyzstan', callingCode: ['996'] },
  { cca2: 'TJ', name: 'Tajikistan', callingCode: ['992'] },
  { cca2: 'TM', name: 'Turkmenistan', callingCode: ['993'] },
  { cca2: 'TR', name: 'Turkey', callingCode: ['90'] },
  { cca2: 'SA', name: 'Saudi Arabia', callingCode: ['966'] },
  { cca2: 'AE', name: 'United Arab Emirates', callingCode: ['971'] },
  { cca2: 'QA', name: 'Qatar', callingCode: ['974'] },
  { cca2: 'KW', name: 'Kuwait', callingCode: ['965'] },
  { cca2: 'BH', name: 'Bahrain', callingCode: ['973'] },
  { cca2: 'OM', name: 'Oman', callingCode: ['968'] },
  { cca2: 'JO', name: 'Jordan', callingCode: ['962'] },
  { cca2: 'LB', name: 'Lebanon', callingCode: ['961'] },
  { cca2: 'SY', name: 'Syria', callingCode: ['963'] },
  { cca2: 'IQ', name: 'Iraq', callingCode: ['964'] },
  { cca2: 'IR', name: 'Iran', callingCode: ['98'] },
  { cca2: 'AF', name: 'Afghanistan', callingCode: ['93'] },
  { cca2: 'PK', name: 'Pakistan', callingCode: ['92'] },
  { cca2: 'BD', name: 'Bangladesh', callingCode: ['880'] },
  { cca2: 'LK', name: 'Sri Lanka', callingCode: ['94'] },
  { cca2: 'NP', name: 'Nepal', callingCode: ['977'] },
  { cca2: 'BT', name: 'Bhutan', callingCode: ['975'] },
  { cca2: 'MV', name: 'Maldives', callingCode: ['960'] },
  { cca2: 'MY', name: 'Malaysia', callingCode: ['60'] },
  { cca2: 'SG', name: 'Singapore', callingCode: ['65'] },
  { cca2: 'TH', name: 'Thailand', callingCode: ['66'] },
  { cca2: 'VN', name: 'Vietnam', callingCode: ['84'] },
  { cca2: 'PH', name: 'Philippines', callingCode: ['63'] },
  { cca2: 'ID', name: 'Indonesia', callingCode: ['62'] },
  { cca2: 'MM', name: 'Myanmar', callingCode: ['95'] },
  { cca2: 'LA', name: 'Laos', callingCode: ['856'] },
  { cca2: 'KH', name: 'Cambodia', callingCode: ['855'] },
  { cca2: 'BN', name: 'Brunei', callingCode: ['673'] },
  { cca2: 'TL', name: 'East Timor', callingCode: ['670'] },
  { cca2: 'MN', name: 'Mongolia', callingCode: ['976'] },
  { cca2: 'NZ', name: 'New Zealand', callingCode: ['64'] },
  { cca2: 'FJ', name: 'Fiji', callingCode: ['679'] },
  { cca2: 'PG', name: 'Papua New Guinea', callingCode: ['675'] },
  { cca2: 'SB', name: 'Solomon Islands', callingCode: ['677'] },
  { cca2: 'VU', name: 'Vanuatu', callingCode: ['678'] },
  { cca2: 'NC', name: 'New Caledonia', callingCode: ['687'] },
  { cca2: 'PF', name: 'French Polynesia', callingCode: ['689'] },
  { cca2: 'TO', name: 'Tonga', callingCode: ['676'] },
  { cca2: 'WS', name: 'Samoa', callingCode: ['685'] },
  { cca2: 'KI', name: 'Kiribati', callingCode: ['686'] },
  { cca2: 'TV', name: 'Tuvalu', callingCode: ['688'] },
  { cca2: 'NR', name: 'Nauru', callingCode: ['674'] },
  { cca2: 'PW', name: 'Palau', callingCode: ['680'] },
  { cca2: 'MH', name: 'Marshall Islands', callingCode: ['692'] },
  { cca2: 'FM', name: 'Micronesia', callingCode: ['691'] },
  { cca2: 'CK', name: 'Cook Islands', callingCode: ['682'] },
  { cca2: 'NU', name: 'Niue', callingCode: ['683'] },
  { cca2: 'TK', name: 'Tokelau', callingCode: ['690'] },
  { cca2: 'AS', name: 'American Samoa', callingCode: ['1'] },
  { cca2: 'GU', name: 'Guam', callingCode: ['1'] },
  { cca2: 'MP', name: 'Northern Mariana Islands', callingCode: ['1'] },
  { cca2: 'PR', name: 'Puerto Rico', callingCode: ['1'] },
  { cca2: 'VI', name: 'U.S. Virgin Islands', callingCode: ['1'] },
  { cca2: 'AI', name: 'Anguilla', callingCode: ['1'] },
  { cca2: 'AG', name: 'Antigua and Barbuda', callingCode: ['1'] },
  { cca2: 'AW', name: 'Aruba', callingCode: ['297'] },
  { cca2: 'BS', name: 'Bahamas', callingCode: ['1'] },
  { cca2: 'BB', name: 'Barbados', callingCode: ['1'] },
  { cca2: 'BZ', name: 'Belize', callingCode: ['501'] },
  { cca2: 'BM', name: 'Bermuda', callingCode: ['1'] },
  { cca2: 'VG', name: 'British Virgin Islands', callingCode: ['1'] },
  { cca2: 'KY', name: 'Cayman Islands', callingCode: ['1'] },
  { cca2: 'CR', name: 'Costa Rica', callingCode: ['506'] },
  { cca2: 'CU', name: 'Cuba', callingCode: ['53'] },
  { cca2: 'DM', name: 'Dominica', callingCode: ['1'] },
  { cca2: 'DO', name: 'Dominican Republic', callingCode: ['1'] },
  { cca2: 'SV', name: 'El Salvador', callingCode: ['503'] },
  { cca2: 'GD', name: 'Grenada', callingCode: ['1'] },
  { cca2: 'GT', name: 'Guatemala', callingCode: ['502'] },
  { cca2: 'HT', name: 'Haiti', callingCode: ['509'] },
  { cca2: 'HN', name: 'Honduras', callingCode: ['504'] },
  { cca2: 'JM', name: 'Jamaica', callingCode: ['1'] },
  { cca2: 'NI', name: 'Nicaragua', callingCode: ['505'] },
  { cca2: 'PA', name: 'Panama', callingCode: ['507'] },
  { cca2: 'KN', name: 'Saint Kitts and Nevis', callingCode: ['1'] },
  { cca2: 'LC', name: 'Saint Lucia', callingCode: ['1'] },
  { cca2: 'VC', name: 'Saint Vincent and the Grenadines', callingCode: ['1'] },
  { cca2: 'TT', name: 'Trinidad and Tobago', callingCode: ['1'] },
  { cca2: 'TC', name: 'Turks and Caicos Islands', callingCode: ['1'] },
  { cca2: 'DZ', name: 'Algeria', callingCode: ['213'] },
  { cca2: 'AO', name: 'Angola', callingCode: ['244'] },
  { cca2: 'BJ', name: 'Benin', callingCode: ['229'] },
  { cca2: 'BW', name: 'Botswana', callingCode: ['267'] },
  { cca2: 'BF', name: 'Burkina Faso', callingCode: ['226'] },
  { cca2: 'BI', name: 'Burundi', callingCode: ['257'] },
  { cca2: 'CM', name: 'Cameroon', callingCode: ['237'] },
  { cca2: 'CV', name: 'Cape Verde', callingCode: ['238'] },
  { cca2: 'CF', name: 'Central African Republic', callingCode: ['236'] },
  { cca2: 'TD', name: 'Chad', callingCode: ['235'] },
  { cca2: 'KM', name: 'Comoros', callingCode: ['269'] },
  { cca2: 'CG', name: 'Congo', callingCode: ['242'] },
  { cca2: 'CD', name: 'Congo, Democratic Republic', callingCode: ['243'] },
  { cca2: 'CI', name: "Côte d'Ivoire", callingCode: ['225'] },
  { cca2: 'DJ', name: 'Djibouti', callingCode: ['253'] },
  { cca2: 'EG', name: 'Egypt', callingCode: ['20'] },
  { cca2: 'GQ', name: 'Equatorial Guinea', callingCode: ['240'] },
  { cca2: 'ER', name: 'Eritrea', callingCode: ['291'] },
  { cca2: 'ET', name: 'Ethiopia', callingCode: ['251'] },
  { cca2: 'GA', name: 'Gabon', callingCode: ['241'] },
  { cca2: 'GM', name: 'Gambia', callingCode: ['220'] },
  { cca2: 'GH', name: 'Ghana', callingCode: ['233'] },
  { cca2: 'GN', name: 'Guinea', callingCode: ['224'] },
  { cca2: 'GW', name: 'Guinea-Bissau', callingCode: ['245'] },
  { cca2: 'KE', name: 'Kenya', callingCode: ['254'] },
  { cca2: 'LS', name: 'Lesotho', callingCode: ['266'] },
  { cca2: 'LR', name: 'Liberia', callingCode: ['231'] },
  { cca2: 'LY', name: 'Libya', callingCode: ['218'] },
  { cca2: 'MG', name: 'Madagascar', callingCode: ['261'] },
  { cca2: 'MW', name: 'Malawi', callingCode: ['265'] },
  { cca2: 'ML', name: 'Mali', callingCode: ['223'] },
  { cca2: 'MR', name: 'Mauritania', callingCode: ['222'] },
  { cca2: 'MU', name: 'Mauritius', callingCode: ['230'] },
  { cca2: 'MA', name: 'Morocco', callingCode: ['212'] },
  { cca2: 'MZ', name: 'Mozambique', callingCode: ['258'] },
  { cca2: 'NA', name: 'Namibia', callingCode: ['264'] },
  { cca2: 'NE', name: 'Niger', callingCode: ['227'] },
  { cca2: 'NG', name: 'Nigeria', callingCode: ['234'] },
  { cca2: 'RW', name: 'Rwanda', callingCode: ['250'] },
  { cca2: 'ST', name: 'São Tomé and Príncipe', callingCode: ['239'] },
  { cca2: 'SN', name: 'Senegal', callingCode: ['221'] },
  { cca2: 'SC', name: 'Seychelles', callingCode: ['248'] },
  { cca2: 'SL', name: 'Sierra Leone', callingCode: ['232'] },
  { cca2: 'SO', name: 'Somalia', callingCode: ['252'] },
  { cca2: 'ZA', name: 'South Africa', callingCode: ['27'] },
  { cca2: 'SS', name: 'South Sudan', callingCode: ['211'] },
  { cca2: 'SD', name: 'Sudan', callingCode: ['249'] },
  { cca2: 'SZ', name: 'Eswatini', callingCode: ['268'] },
  { cca2: 'TZ', name: 'Tanzania', callingCode: ['255'] },
  { cca2: 'TG', name: 'Togo', callingCode: ['228'] },
  { cca2: 'TN', name: 'Tunisia', callingCode: ['216'] },
  { cca2: 'UG', name: 'Uganda', callingCode: ['256'] },
  { cca2: 'ZM', name: 'Zambia', callingCode: ['260'] },
  { cca2: 'ZW', name: 'Zimbabwe', callingCode: ['263'] },
];

export const getCountryByCode = (code: string): Country | undefined => {
  return countries.find((country) => country.cca2 === code.toUpperCase());
};

export const getCountryByCallingCode = (code: string): Country | undefined => {
  return countries.find((country) => country.callingCode.includes(code));
};

export const getCountryByName = (name: string): Country | undefined => {
  return countries.find((country) => country.name.toLowerCase().includes(name.toLowerCase()));
};

export const searchCountries = (query: string): Country[] => {
  const lowercaseQuery = query.toLowerCase();
  return countries.filter(
    (country) =>
      country.name.toLowerCase().includes(lowercaseQuery) ||
      country.cca2.toLowerCase().includes(lowercaseQuery) ||
      country.callingCode.some((code) => code.includes(lowercaseQuery))
  );
};
