export enum Routes {
  Login = '/(auth)/login',
  Verify = '/login/verify',
  Onboarding = '/(auth)/onboarding',
  Signup = '/(auth)/signup',
  SoftSignup = '/(auth)/soft-signup',
  ThankYou = '/(app)/thank-you',
  Home = '/(app)/(tabs)/home',
  Product = '/(app)/(tabs)/product',
  Account = '/(app)/(tabs)/account',
  MyAddresses = '/account/my-addresses',
  ModifyAddress = '/address',
  Categories = '/product/categories',
  ProductListing = '/product/categories/[id]',
  ProductDetails = '/product/[id]',
  Factory = '/factory/[id]',
  Orders = '/(app)/(tabs)/orders',
  OrderDocuments = '/order/order-documents',
  OrderDetails = '/order/[id]',
  ShipmentDetails = '/order/shipment-details',
  Cart = '/order/cart',
  PaymentInstructions = '/payment/payment-instructions',
  Checkout = '/order/checkout',
  ProductSearch = '/product/search/[search_text]',
  OrderProtections = '/order/protections',
  PdfViewer = '/order/pdf-viewer',
}
